name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7' 
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Installs requirements
      run: pip install -r requirements.txt
    - name: Runs tests
      run: pytest
